import { Tour } from "../types";
import { 
  Shield, 
  Users,
  Settings,
  Database,
  FileKey,
  Activity,
  Bell,
  Lock,
  UserPlus,
  Trash2,
  Download
} from "lucide-react";

/**
 * Admin Portal Tour - System administration features
 */
export const adminPortalTour: Tour = {
  id: "admin-portal-tour",
  name: "Admin Portal Guide",
  description: "Learn how to manage users, permissions, and system settings",
  route: "/admin",
  triggerOnFirstVisit: true,
  autoStart: true,
  showOnce: true,
  priority: 4,
  steps: [
    {
      id: "welcome",
      title: "Admin Portal",
      description: "Manage users, permissions, system settings, and monitor activity. This area is restricted to administrators only.",
      icon: Shield,
      iconColor: "text-red-600",
      iconBgColor: "bg-red-100 dark:bg-red-900/30",
      type: "modal",
    },
    {
      id: "user-management",
      title: "User Management",
      description: "View all users, their roles, and last activity. Add new users, reset passwords, or disable accounts from here.",
      targetSelector: "[data-testid='user-list'], .user-table, table",
      placement: "top",
      spotlightPadding: 8,
      icon: Users,
      iconColor: "text-blue-600",
      iconBgColor: "bg-blue-100 dark:bg-blue-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "add-user",
      title: "Add New User",
      description: "Invite new team members by email. Assign their role (Admin, Manager, User) and project permissions during setup.",
      targetSelector: "[data-testid='add-user'], button[aria-label*='add user'], button:has(svg.lucide-user-plus)",
      placement: "bottom",
      spotlightPadding: 8,
      icon: UserPlus,
      iconColor: "text-green-600",
      iconBgColor: "bg-green-100 dark:bg-green-900/30",
      type: "spotlight",
    },
    {
      id: "roles-permissions",
      title: "Roles & Permissions",
      description: "Configure what each role can access and modify. Create custom roles for specific team needs.",
      targetSelector: "[data-testid='roles-tab'], button[aria-label*='roles'], [role='tab']:has-text('Roles')",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Lock,
      iconColor: "text-purple-600",
      iconBgColor: "bg-purple-100 dark:bg-purple-900/30",
      type: "spotlight",
    },
    {
      id: "activity-log",
      title: "Activity Log",
      description: "Monitor all system activity: logins, document changes, user actions. Filter by user, action type, or date for auditing.",
      targetSelector: "[data-testid='activity-log'], .activity-section, .audit-log",
      placement: "right",
      spotlightPadding: 8,
      icon: Activity,
      iconColor: "text-amber-600",
      iconBgColor: "bg-amber-100 dark:bg-amber-900/30",
      type: "spotlight",
    },
    {
      id: "system-settings",
      title: "System Settings",
      description: "Configure global settings: company branding, default values, email templates, and integration connections.",
      targetSelector: "[data-testid='system-settings'], .settings-panel, [role='tab']:has-text('Settings')",
      placement: "left",
      spotlightPadding: 8,
      icon: Settings,
      iconColor: "text-gray-600",
      iconBgColor: "bg-gray-100 dark:bg-gray-900/30",
      type: "spotlight",
    },
    {
      id: "data-management",
      title: "Data Management",
      description: "Backup data, export records, or manage storage. Schedule automatic backups for data protection.",
      targetSelector: "[data-testid='data-management'], .backup-section",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Database,
      iconColor: "text-cyan-600",
      iconBgColor: "bg-cyan-100 dark:bg-cyan-900/30",
      type: "spotlight",
      highlightActions: [
        {
          label: "Create Backup",
          onClick: () => {},
          variant: "outline",
          icon: Download,
        },
      ],
    },
    {
      id: "api-keys",
      title: "API & Integrations",
      description: "Manage API keys for external integrations. Connect to accounting software, project management tools, and more.",
      targetSelector: "[data-testid='api-keys'], .integrations-section",
      placement: "left",
      spotlightPadding: 8,
      icon: FileKey,
      iconColor: "text-indigo-600",
      iconBgColor: "bg-indigo-100 dark:bg-indigo-900/30",
      type: "tooltip",
    },
    {
      id: "complete",
      title: "Admin Portal Ready!",
      description: "You have full control over your system. Remember: With great power comes great responsibility. All actions are logged.",
      icon: Shield,
      iconColor: "text-primary",
      iconBgColor: "bg-primary/10",
      type: "modal",
    },
  ],
};

export default adminPortalTour;
