import { Tour } from "../types";
import { 
  Cable, 
  Plus,
  Table,
  Calculator,
  Download,
  Settings,
  Copy,
  Trash2,
  Save,
  FileSpreadsheet
} from "lucide-react";

/**
 * Cable Schedule Tour - Detailed cable schedule management
 */
export const cableScheduleTour: Tour = {
  id: "cable-schedule-tour",
  name: "Cable Schedule Guide",
  description: "Master cable schedule creation and management",
  route: "/cable-schedule",
  triggerOnFirstVisit: true,
  autoStart: true,
  showOnce: true,
  priority: 7,
  steps: [
    {
      id: "welcome",
      title: "Cable Schedule Manager",
      description: "Create detailed cable schedules with automatic calculations for sizing, voltage drop, and costs. All based on SANS 10142 standards.",
      icon: Cable,
      iconColor: "text-amber-600",
      iconBgColor: "bg-amber-100 dark:bg-amber-900/30",
      type: "modal",
    },
    {
      id: "schedule-header",
      title: "Schedule Information",
      description: "Each schedule has a name, number, revision, and associated layout. This information appears on exported documents.",
      targetSelector: "[data-testid='schedule-header'], .schedule-header, .schedule-info",
      placement: "bottom",
      spotlightPadding: 8,
      icon: FileSpreadsheet,
      iconColor: "text-blue-600",
      iconBgColor: "bg-blue-100 dark:bg-blue-900/30",
      type: "spotlight",
    },
    {
      id: "cable-table",
      title: "Cable Entries Table",
      description: "View all cables in a detailed table. Each row shows: tag, from/to locations, size, type, length, and calculated values.",
      targetSelector: "[data-testid='cable-table'], table, .cable-grid",
      placement: "top",
      spotlightPadding: 8,
      icon: Table,
      iconColor: "text-emerald-600",
      iconBgColor: "bg-emerald-100 dark:bg-emerald-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "add-cable",
      title: "Add New Cable",
      description: "Click to add a new cable entry. Enter source and destination, load details, and the system recommends appropriate cable sizing.",
      targetSelector: "[data-testid='add-cable'], button[aria-label*='add'], button:has(svg.lucide-plus)",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Plus,
      iconColor: "text-green-600",
      iconBgColor: "bg-green-100 dark:bg-green-900/30",
      type: "spotlight",
    },
    {
      id: "calculations",
      title: "Automatic Calculations",
      description: "Voltage drop, derating factors, and cable sizing are calculated automatically based on your inputs and project settings.",
      targetSelector: "[data-testid='calculations'], .calculation-summary, .calc-panel",
      placement: "left",
      spotlightPadding: 8,
      icon: Calculator,
      iconColor: "text-purple-600",
      iconBgColor: "bg-purple-100 dark:bg-purple-900/30",
      type: "spotlight",
    },
    {
      id: "cable-settings",
      title: "Calculation Settings",
      description: "Configure calculation parameters: ambient temperature, grouping factors, installation methods, and safety margins.",
      targetSelector: "[data-testid='settings-button'], button[aria-label*='settings']",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Settings,
      iconColor: "text-gray-600",
      iconBgColor: "bg-gray-100 dark:bg-gray-900/30",
      type: "spotlight",
    },
    {
      id: "bulk-actions",
      title: "Bulk Actions",
      description: "Select multiple cables to copy, delete, or update together. Great for making changes across similar cable entries.",
      targetSelector: "[data-testid='bulk-actions'], .bulk-action-bar, .selection-toolbar",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Copy,
      iconColor: "text-cyan-600",
      iconBgColor: "bg-cyan-100 dark:bg-cyan-900/30",
      type: "tooltip",
    },
    {
      id: "export",
      title: "Export Schedule",
      description: "Generate professional PDF or Excel exports. PDF includes cover page and summary. Excel is ready for further editing.",
      targetSelector: "[data-testid='export-button'], button[aria-label*='export'], button:has-text('Export')",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Download,
      iconColor: "text-indigo-600",
      iconBgColor: "bg-indigo-100 dark:bg-indigo-900/30",
      type: "spotlight",
      highlightActions: [
        {
          label: "Export PDF",
          onClick: () => {},
          variant: "default",
          icon: Download,
        },
        {
          label: "Export Excel",
          onClick: () => {},
          variant: "outline",
          icon: FileSpreadsheet,
        },
      ],
    },
    {
      id: "complete",
      title: "Cable Schedule Ready!",
      description: "You're now equipped to create comprehensive cable schedules. Start by adding your first cable entry or import from a floor plan.",
      icon: Cable,
      iconColor: "text-primary",
      iconBgColor: "bg-primary/10",
      type: "modal",
    },
  ],
};

export default cableScheduleTour;
