import { Tour } from "../types";
import { 
  Users, 
  FileText,
  MessageSquare,
  Download,
  Eye,
  CheckCircle,
  Clock,
  Bell,
  Share2,
  Shield
} from "lucide-react";

/**
 * Client Portal Tour - Client-facing document sharing and approvals
 */
export const clientPortalTour: Tour = {
  id: "client-portal-tour",
  name: "Client Portal Guide",
  description: "Learn how to use the client portal for document review and approvals",
  route: "/client-portal",
  triggerOnFirstVisit: true,
  autoStart: true,
  showOnce: true,
  priority: 5,
  steps: [
    {
      id: "welcome",
      title: "Welcome to Client Portal",
      description: "This is your secure hub for reviewing documents, providing feedback, and approving deliverables. Let's walk through the key features.",
      icon: Users,
      iconColor: "text-primary",
      iconBgColor: "bg-primary/10",
      type: "modal",
    },
    {
      id: "project-selector",
      title: "Your Projects",
      description: "Switch between projects you have access to. Each project shows its current status and documents pending your review.",
      targetSelector: "[data-testid='project-selector'], .project-dropdown, select",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Share2,
      iconColor: "text-blue-600",
      iconBgColor: "bg-blue-100 dark:bg-blue-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "pending-reviews",
      title: "Pending Reviews",
      description: "Documents awaiting your review are highlighted here. Red badges indicate urgent items approaching deadlines.",
      targetSelector: "[data-testid='pending-reviews'], .pending-section, .review-queue",
      placement: "right",
      spotlightPadding: 8,
      icon: Clock,
      iconColor: "text-amber-600",
      iconBgColor: "bg-amber-100 dark:bg-amber-900/30",
      type: "spotlight",
    },
    {
      id: "document-list",
      title: "Document Library",
      description: "View all shared documents organized by category. Filter by type (drawings, reports, schedules) or status (draft, for review, approved).",
      targetSelector: "[data-testid='document-list'], .document-grid, .file-list",
      placement: "top",
      spotlightPadding: 8,
      icon: FileText,
      iconColor: "text-purple-600",
      iconBgColor: "bg-purple-100 dark:bg-purple-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "document-preview",
      title: "Document Preview",
      description: "Click any document to open a full preview. PDFs and drawings open in an interactive viewer with zoom and annotation tools.",
      targetSelector: "[data-testid='document-preview'], .preview-panel, .document-viewer",
      placement: "left",
      spotlightPadding: 8,
      icon: Eye,
      iconColor: "text-cyan-600",
      iconBgColor: "bg-cyan-100 dark:bg-cyan-900/30",
      type: "spotlight",
    },
    {
      id: "comments",
      title: "Comments & Feedback",
      description: "Add comments on documents or specific areas. Your team will be notified and can respond directly. All comments are tracked for reference.",
      targetSelector: "[data-testid='comments-panel'], .comments-section, .feedback-panel",
      placement: "left",
      spotlightPadding: 8,
      icon: MessageSquare,
      iconColor: "text-emerald-600",
      iconBgColor: "bg-emerald-100 dark:bg-emerald-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "approval-workflow",
      title: "Approve Documents",
      description: "When you're satisfied with a document, click Approve to sign off. You can also request changes or reject with comments.",
      targetSelector: "[data-testid='approval-buttons'], .approval-actions, button[aria-label*='approve']",
      placement: "bottom",
      spotlightPadding: 8,
      icon: CheckCircle,
      iconColor: "text-green-600",
      iconBgColor: "bg-green-100 dark:bg-green-900/30",
      type: "spotlight",
      highlightActions: [
        {
          label: "Approve",
          onClick: () => {},
          variant: "default",
          icon: CheckCircle,
        },
        {
          label: "Request Changes",
          onClick: () => {},
          variant: "outline",
          icon: MessageSquare,
        },
      ],
    },
    {
      id: "downloads",
      title: "Download Documents",
      description: "Download any document for offline review. Choose between original format or PDF. Bulk download is available for multiple files.",
      targetSelector: "[data-testid='download-button'], button[aria-label*='download']",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Download,
      iconColor: "text-indigo-600",
      iconBgColor: "bg-indigo-100 dark:bg-indigo-900/30",
      type: "tooltip",
    },
    {
      id: "notifications",
      title: "Stay Updated",
      description: "Receive notifications when new documents are shared or team members respond to your comments. Configure preferences in settings.",
      targetSelector: "[data-testid='notifications'], .notification-bell",
      placement: "bottom-end",
      spotlightPadding: 8,
      icon: Bell,
      iconColor: "text-orange-600",
      iconBgColor: "bg-orange-100 dark:bg-orange-900/30",
      type: "tooltip",
    },
    {
      id: "complete",
      title: "Portal Ready!",
      description: "You're all set to collaborate on your project. Start by reviewing any pending documents, or browse the document library.",
      icon: Users,
      iconColor: "text-primary",
      iconBgColor: "bg-primary/10",
      type: "modal",
    },
  ],
};

export default clientPortalTour;
