import { Tour } from "../types";
import { 
  LayoutDashboard, 
  BarChart3,
  Activity,
  Clock,
  Users,
  Bell,
  Calendar,
  TrendingUp,
  CheckCircle,
  AlertTriangle,
  FolderKanban
} from "lucide-react";

/**
 * Dashboard Tour - Main dashboard overview and features
 */
export const dashboardTour: Tour = {
  id: "dashboard-tour",
  name: "Dashboard Overview",
  description: "Get familiar with your main dashboard and key metrics",
  route: "/dashboard",
  triggerOnFirstVisit: true,
  autoStart: true,
  showOnce: true,
  priority: 10,
  steps: [
    {
      id: "welcome",
      title: "Welcome to Your Dashboard",
      description: "This is your command center for monitoring projects, tracking progress, and staying on top of important updates. Let's take a quick tour.",
      icon: LayoutDashboard,
      iconColor: "text-primary",
      iconBgColor: "bg-primary/10",
      type: "modal",
    },
    {
      id: "overview-stats",
      title: "Key Metrics",
      description: "These cards show your most important metrics at a glance: active projects, pending tasks, team activity, and upcoming deadlines.",
      targetSelector: "[data-testid='stats-cards'], .stats-container, .dashboard-stats",
      placement: "bottom",
      spotlightPadding: 12,
      icon: BarChart3,
      iconColor: "text-blue-600",
      iconBgColor: "bg-blue-100 dark:bg-blue-900/30",
      type: "spotlight",
    },
    {
      id: "activity-feed",
      title: "Recent Activity",
      description: "Stay updated with the latest actions across your projects. See who made changes, what was updated, and when it happened.",
      targetSelector: "[data-testid='activity-feed'], .activity-feed, .recent-activity",
      placement: "left",
      spotlightPadding: 8,
      icon: Activity,
      iconColor: "text-emerald-600",
      iconBgColor: "bg-emerald-100 dark:bg-emerald-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "project-progress",
      title: "Project Progress",
      description: "Visual progress indicators show how each project is advancing. Click any project for detailed breakdown and timeline.",
      targetSelector: "[data-testid='project-progress'], .project-progress, .progress-chart",
      placement: "right",
      spotlightPadding: 8,
      icon: TrendingUp,
      iconColor: "text-purple-600",
      iconBgColor: "bg-purple-100 dark:bg-purple-900/30",
      type: "spotlight",
    },
    {
      id: "upcoming-deadlines",
      title: "Upcoming Deadlines",
      description: "Never miss a deadline! This section highlights tasks and milestones coming up in the next week. Red items need immediate attention.",
      targetSelector: "[data-testid='deadlines'], .deadlines-section, .upcoming-tasks",
      placement: "left",
      spotlightPadding: 8,
      icon: Clock,
      iconColor: "text-amber-600",
      iconBgColor: "bg-amber-100 dark:bg-amber-900/30",
      type: "spotlight",
    },
    {
      id: "team-overview",
      title: "Team at a Glance",
      description: "See who's online, what they're working on, and their current workload. Great for coordinating efforts across your team.",
      targetSelector: "[data-testid='team-overview'], .team-section, .team-activity",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Users,
      iconColor: "text-cyan-600",
      iconBgColor: "bg-cyan-100 dark:bg-cyan-900/30",
      type: "tooltip",
    },
    {
      id: "notifications",
      title: "Notifications Center",
      description: "Access all your notifications here. You'll see mentions, approvals needed, and system alerts. Configure notification preferences in settings.",
      targetSelector: "[data-testid='notifications'], .notifications-bell, button[aria-label*='notification']",
      placement: "bottom-end",
      spotlightPadding: 8,
      icon: Bell,
      iconColor: "text-orange-600",
      iconBgColor: "bg-orange-100 dark:bg-orange-900/30",
      type: "spotlight",
      waitForElement: true,
    },
    {
      id: "quick-actions",
      title: "Quick Access",
      description: "Use the sidebar to quickly navigate to projects, documents, reports, and settings. Your most-used items are always accessible.",
      targetSelector: "[data-testid='sidebar'], .sidebar, nav[role='navigation']",
      placement: "right",
      spotlightPadding: 8,
      icon: FolderKanban,
      iconColor: "text-indigo-600",
      iconBgColor: "bg-indigo-100 dark:bg-indigo-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "complete",
      title: "Dashboard Ready!",
      description: "You're all set to use your dashboard effectively. Remember, you can customize the layout in settings to show what matters most to you.",
      icon: CheckCircle,
      iconColor: "text-green-600",
      iconBgColor: "bg-green-100 dark:bg-green-900/30",
      type: "modal",
    },
  ],
};

export default dashboardTour;
