import { Tour } from "../types";
import { 
  Map, 
  Move,
  ZoomIn,
  Ruler,
  Layers,
  MousePointer,
  Cable,
  Save,
  Upload,
  Image,
  Eye
} from "lucide-react";

/**
 * Floor Plan Tour - Interactive floor plan drawing and cable routing
 */
export const floorPlanTour: Tour = {
  id: "floor-plan-tour",
  name: "Floor Plan Guide",
  description: "Learn how to use the floor plan tool for cable routing and measurements",
  route: "/floor-plan",
  triggerOnFirstVisit: true,
  autoStart: true,
  showOnce: true,
  priority: 6,
  steps: [
    {
      id: "welcome",
      title: "Floor Plan Designer",
      description: "Draw cable routes directly on floor plans, measure distances, and export to cable schedules. This tool streamlines your electrical design process.",
      icon: Map,
      iconColor: "text-primary",
      iconBgColor: "bg-primary/10",
      type: "modal",
    },
    {
      id: "canvas",
      title: "Drawing Canvas",
      description: "This is your main workspace. Pan by dragging, zoom with scroll wheel or pinch. The grid helps maintain scale and alignment.",
      targetSelector: "[data-testid='canvas'], canvas, .floor-plan-canvas",
      placement: "top",
      spotlightPadding: 0,
      icon: Move,
      iconColor: "text-blue-600",
      iconBgColor: "bg-blue-100 dark:bg-blue-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "zoom-controls",
      title: "Zoom & Navigation",
      description: "Use these controls to zoom in/out and reset the view. Fit to screen shows the entire plan. You can also use keyboard shortcuts.",
      targetSelector: "[data-testid='zoom-controls'], .zoom-buttons, .navigation-controls",
      placement: "left",
      spotlightPadding: 8,
      icon: ZoomIn,
      iconColor: "text-purple-600",
      iconBgColor: "bg-purple-100 dark:bg-purple-900/30",
      type: "spotlight",
    },
    {
      id: "tool-palette",
      title: "Drawing Tools",
      description: "Select tools for different tasks: Pointer for selection, Line for cables, Rectangle for equipment, Text for labels. Each tool has specific options.",
      targetSelector: "[data-testid='tool-palette'], .tool-bar, .drawing-tools",
      placement: "right",
      spotlightPadding: 8,
      icon: MousePointer,
      iconColor: "text-emerald-600",
      iconBgColor: "bg-emerald-100 dark:bg-emerald-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "cable-tool",
      title: "Cable Drawing",
      description: "Draw cable routes by clicking points. Double-click to end a cable. The system automatically calculates total length based on your scale settings.",
      targetSelector: "[data-testid='cable-tool'], button[aria-label*='cable']",
      placement: "right",
      spotlightPadding: 8,
      icon: Cable,
      iconColor: "text-amber-600",
      iconBgColor: "bg-amber-100 dark:bg-amber-900/30",
      type: "spotlight",
    },
    {
      id: "measurement",
      title: "Measurements",
      description: "Use the ruler tool to measure distances. Click and drag to create a measurement line. Measurements use your defined scale (e.g., 1:100).",
      targetSelector: "[data-testid='ruler-tool'], button[aria-label*='measure'], button[aria-label*='ruler']",
      placement: "right",
      spotlightPadding: 8,
      icon: Ruler,
      iconColor: "text-cyan-600",
      iconBgColor: "bg-cyan-100 dark:bg-cyan-900/30",
      type: "spotlight",
    },
    {
      id: "layers",
      title: "Layer Management",
      description: "Organize elements on different layers: Background for floor plan image, Cables for routes, Labels for text. Toggle visibility and lock layers.",
      targetSelector: "[data-testid='layers-panel'], .layers-list, .layer-controls",
      placement: "left",
      spotlightPadding: 8,
      icon: Layers,
      iconColor: "text-indigo-600",
      iconBgColor: "bg-indigo-100 dark:bg-indigo-900/30",
      type: "spotlight",
    },
    {
      id: "import-image",
      title: "Import Floor Plan",
      description: "Upload a floor plan image (PDF or image file) as your base layer. Set the scale after import to ensure accurate measurements.",
      targetSelector: "[data-testid='import-button'], button[aria-label*='import'], button[aria-label*='upload']",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Upload,
      iconColor: "text-pink-600",
      iconBgColor: "bg-pink-100 dark:bg-pink-900/30",
      type: "spotlight",
    },
    {
      id: "save-export",
      title: "Save & Export",
      description: "Save your work to the project. Export cable data to cable schedules, or download as an image for documentation.",
      targetSelector: "[data-testid='save-button'], button[aria-label*='save']",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Save,
      iconColor: "text-green-600",
      iconBgColor: "bg-green-100 dark:bg-green-900/30",
      type: "spotlight",
      highlightActions: [
        {
          label: "Save Project",
          onClick: () => {},
          variant: "default",
          icon: Save,
        },
        {
          label: "Export Image",
          onClick: () => {},
          variant: "outline",
          icon: Image,
        },
      ],
    },
    {
      id: "complete",
      title: "Floor Plan Ready!",
      description: "You're now ready to design cable routes on floor plans. Start by importing a floor plan image, then use the cable tool to draw routes.",
      icon: Map,
      iconColor: "text-primary",
      iconBgColor: "bg-primary/10",
      type: "modal",
    },
  ],
};

export default floorPlanTour;
