import { Tour } from "../types";
import { 
  Zap, 
  FileText,
  Settings,
  Calculator,
  Download,
  Building,
  MapPin,
  Gauge,
  AlertTriangle,
  CheckCircle,
  Table
} from "lucide-react";

/**
 * Generator Report Tour - Electrical load calculations and reports
 */
export const generatorTour: Tour = {
  id: "generator-report-tour",
  name: "Generator Report Guide",
  description: "Learn how to create electrical load and generator sizing reports",
  route: "/generator",
  triggerOnFirstVisit: true,
  autoStart: true,
  showOnce: true,
  priority: 6,
  steps: [
    {
      id: "welcome",
      title: "Generator Report System",
      description: "Create comprehensive bulk services and generator sizing reports compliant with SANS 10142. Calculate maximum demand, diversity factors, and recommended generator sizes.",
      icon: Zap,
      iconColor: "text-amber-600",
      iconBgColor: "bg-amber-100 dark:bg-amber-900/30",
      type: "modal",
    },
    {
      id: "project-info",
      title: "Project Information",
      description: "Enter project details: name, location, building type, and supply authority requirements. This information appears on the generated report.",
      targetSelector: "[data-testid='project-info'], .project-info-form, form:first-of-type",
      placement: "right",
      spotlightPadding: 8,
      icon: Building,
      iconColor: "text-blue-600",
      iconBgColor: "bg-blue-100 dark:bg-blue-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "calculation-method",
      title: "Calculation Method",
      description: "Choose your calculation method: VA per square meter for commercial, load-by-load for industrial, or template-based for residential. Each method follows SANS 10142 requirements.",
      targetSelector: "[data-testid='calc-method'], .calculation-method, [role='radiogroup']",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Calculator,
      iconColor: "text-purple-600",
      iconBgColor: "bg-purple-100 dark:bg-purple-900/30",
      type: "spotlight",
    },
    {
      id: "load-schedule",
      title: "Load Schedule",
      description: "Enter individual loads with their ratings, quantities, and diversity factors. The system calculates running and starting loads automatically.",
      targetSelector: "[data-testid='load-schedule'], .load-table, table",
      placement: "top",
      spotlightPadding: 8,
      icon: Table,
      iconColor: "text-emerald-600",
      iconBgColor: "bg-emerald-100 dark:bg-emerald-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "diversity-factors",
      title: "Diversity & Demand Factors",
      description: "Adjust diversity factors based on load types and usage patterns. The system suggests values based on SANS 10142 tables for your building type.",
      targetSelector: "[data-testid='diversity-factors'], .diversity-panel, .factors-section",
      placement: "left",
      spotlightPadding: 8,
      icon: Gauge,
      iconColor: "text-cyan-600",
      iconBgColor: "bg-cyan-100 dark:bg-cyan-900/30",
      type: "spotlight",
    },
    {
      id: "results-summary",
      title: "Calculation Results",
      description: "View calculated results: total connected load, maximum demand, and recommended supply size. Warnings highlight potential issues with your design.",
      targetSelector: "[data-testid='results-summary'], .results-panel, .calculation-results",
      placement: "left",
      spotlightPadding: 12,
      icon: CheckCircle,
      iconColor: "text-green-600",
      iconBgColor: "bg-green-100 dark:bg-green-900/30",
      type: "spotlight",
    },
    {
      id: "generator-sizing",
      title: "Generator Sizing",
      description: "Get recommended generator sizes based on your load analysis. The system accounts for starting currents, future expansion, and redundancy requirements.",
      targetSelector: "[data-testid='generator-sizing'], .generator-recommendation",
      placement: "right",
      spotlightPadding: 8,
      icon: Zap,
      iconColor: "text-amber-600",
      iconBgColor: "bg-amber-100 dark:bg-amber-900/30",
      type: "spotlight",
    },
    {
      id: "generate-report",
      title: "Generate Report",
      description: "Create a professional PDF report suitable for submission to supply authorities. Includes all calculations, drawings placeholders, and compliance notes.",
      targetSelector: "[data-testid='generate-report'], button[aria-label*='generate'], button:has-text('Generate')",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Download,
      iconColor: "text-indigo-600",
      iconBgColor: "bg-indigo-100 dark:bg-indigo-900/30",
      type: "spotlight",
      highlightActions: [
        {
          label: "Generate PDF",
          onClick: () => {},
          variant: "default",
          icon: FileText,
        },
      ],
    },
    {
      id: "complete",
      title: "Generator Reports Ready!",
      description: "You're now ready to create professional bulk services and generator sizing reports. All calculations follow SANS 10142 standards.",
      icon: Zap,
      iconColor: "text-primary",
      iconBgColor: "bg-primary/10",
      type: "modal",
    },
  ],
};

export default generatorTour;
