import { Tour } from "../types";
import { 
  Library, 
  Search,
  Filter,
  Plus,
  FileSpreadsheet,
  Tag,
  FolderTree,
  Download,
  Upload,
  Edit,
  Trash2
} from "lucide-react";

/**
 * Libraries Tour - Master Library, Contact Library, Material Library
 */
export const librariesTour: Tour = {
  id: "libraries-tour",
  name: "Libraries Guide",
  description: "Learn how to use and manage your master libraries",
  route: "/libraries",
  triggerOnFirstVisit: true,
  autoStart: true,
  showOnce: true,
  priority: 8,
  steps: [
    {
      id: "welcome",
      title: "Welcome to Libraries",
      description: "Libraries contain your reusable data: materials, contacts, templates, and rates. Data here is shared across all projects, saving you time and ensuring consistency.",
      icon: Library,
      iconColor: "text-primary",
      iconBgColor: "bg-primary/10",
      type: "modal",
    },
    {
      id: "library-tabs",
      title: "Library Categories",
      description: "Switch between different libraries using these tabs: Materials for electrical components, Contacts for clients and suppliers, Rates for pricing, and Templates for documents.",
      targetSelector: "[role='tablist'], .library-tabs, .tabs-list",
      placement: "bottom",
      spotlightPadding: 8,
      icon: FolderTree,
      iconColor: "text-blue-600",
      iconBgColor: "bg-blue-100 dark:bg-blue-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "search-library",
      title: "Search & Filter",
      description: "Quickly find items by name, code, or category. Use advanced filters to narrow down by type, supplier, or price range.",
      targetSelector: "[data-testid='library-search'], input[type='search'], .search-input",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Search,
      iconColor: "text-purple-600",
      iconBgColor: "bg-purple-100 dark:bg-purple-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "category-filter",
      title: "Category Navigation",
      description: "Browse items by category using this sidebar. Categories are organized hierarchically for easy navigation.",
      targetSelector: "[data-testid='category-tree'], .category-sidebar, .category-list",
      placement: "right",
      spotlightPadding: 8,
      icon: Tag,
      iconColor: "text-emerald-600",
      iconBgColor: "bg-emerald-100 dark:bg-emerald-900/30",
      type: "spotlight",
    },
    {
      id: "item-list",
      title: "Item List",
      description: "View all items in a sortable table. Click column headers to sort. Each row shows key details like name, code, unit, and current rate.",
      targetSelector: "[data-testid='library-table'], table, .data-table",
      placement: "top",
      spotlightPadding: 8,
      icon: FileSpreadsheet,
      iconColor: "text-amber-600",
      iconBgColor: "bg-amber-100 dark:bg-amber-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "add-item",
      title: "Add New Item",
      description: "Click here to add new items to the library. Enter details like name, code, category, unit, and rates. Items become immediately available in all projects.",
      targetSelector: "[data-testid='add-item'], button[aria-label*='add'], button:has(svg.lucide-plus)",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Plus,
      iconColor: "text-green-600",
      iconBgColor: "bg-green-100 dark:bg-green-900/30",
      type: "spotlight",
    },
    {
      id: "import-export",
      title: "Import & Export",
      description: "Bulk import items from Excel files or export your library for backup. Great for migrating data or sharing with team members.",
      targetSelector: "[data-testid='import-export'], .import-export-buttons",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Upload,
      iconColor: "text-cyan-600",
      iconBgColor: "bg-cyan-100 dark:bg-cyan-900/30",
      type: "tooltip",
      highlightActions: [
        {
          label: "Import Excel",
          onClick: () => {},
          variant: "outline",
          icon: Upload,
        },
        {
          label: "Export",
          onClick: () => {},
          variant: "outline",
          icon: Download,
        },
      ],
    },
    {
      id: "edit-delete",
      title: "Edit & Delete",
      description: "Click any row to edit item details. Use the delete button to remove items. Note: Items used in projects cannot be deleted but can be archived.",
      icon: Edit,
      iconColor: "text-gray-600",
      iconBgColor: "bg-gray-100 dark:bg-gray-900/30",
      type: "modal",
    },
    {
      id: "complete",
      title: "Libraries Ready!",
      description: "You're now ready to manage your libraries effectively. Changes here automatically sync to all projects using these items.",
      icon: Library,
      iconColor: "text-primary",
      iconBgColor: "bg-primary/10",
      type: "modal",
    },
  ],
};

export default librariesTour;
