import { Tour } from "../types";
import { 
  FolderKanban, 
  Search, 
  Filter,
  Plus,
  Building,
  FileText,
  Settings,
  MapPin,
  Calendar,
  Users,
  Bookmark,
  LayoutGrid,
  List
} from "lucide-react";

/**
 * Projects Page Tour - Comprehensive walkthrough of project management
 */
export const projectsTour: Tour = {
  id: "projects-page-tour",
  name: "Projects Overview",
  description: "Learn how to manage your projects effectively",
  route: "/projects",
  triggerOnFirstVisit: true,
  autoStart: true,
  showOnce: true,
  priority: 10,
  steps: [
    {
      id: "welcome",
      title: "Welcome to Projects",
      description: "This is your project management hub where you can view, search, and manage all your electrical engineering projects. Let's explore the key features.",
      icon: FolderKanban,
      iconColor: "text-primary",
      iconBgColor: "bg-primary/10",
      type: "modal",
    },
    {
      id: "search-bar",
      title: "Search Projects",
      description: "Quickly find any project by typing its name, number, or client name. The search updates results as you type.",
      targetSelector: "[data-testid='project-search'], input[type='search'], input[placeholder*='search' i]",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Search,
      iconColor: "text-blue-600",
      iconBgColor: "bg-blue-100 dark:bg-blue-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "filter-controls",
      title: "Filter & Sort",
      description: "Use filters to narrow down projects by status (active, completed, archived), client, or date range. Sort by name, date, or progress.",
      targetSelector: "[data-testid='filter-button'], button[aria-label*='filter' i], .filter-controls",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Filter,
      iconColor: "text-purple-600",
      iconBgColor: "bg-purple-100 dark:bg-purple-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "view-toggle",
      title: "View Options",
      description: "Switch between grid view for visual overview or list view for detailed information. Your preference is saved automatically.",
      targetSelector: "[data-testid='view-toggle'], .view-toggle, button[aria-label*='view']",
      placement: "bottom",
      spotlightPadding: 8,
      icon: LayoutGrid,
      iconColor: "text-emerald-600",
      iconBgColor: "bg-emerald-100 dark:bg-emerald-900/30",
      type: "tooltip",
    },
    {
      id: "project-card",
      title: "Project Cards",
      description: "Each card displays key project information: name, client, status, progress, and important dates. Click any card to open the project.",
      targetSelector: "[data-testid='project-card'], .project-card, article:first-of-type",
      placement: "right",
      spotlightPadding: 12,
      icon: Building,
      iconColor: "text-amber-600",
      iconBgColor: "bg-amber-100 dark:bg-amber-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "project-status",
      title: "Status Indicators",
      description: "Color-coded badges show project status at a glance: Green for active, Blue for completed, Yellow for on-hold, Gray for archived.",
      icon: Bookmark,
      iconColor: "text-green-600",
      iconBgColor: "bg-green-100 dark:bg-green-900/30",
      type: "modal",
    },
    {
      id: "quick-actions",
      title: "Quick Actions",
      description: "Hover over a project card to reveal quick actions: open documents, view schedule, access settings, or archive the project.",
      targetSelector: "[data-testid='project-card'] button, .project-actions",
      placement: "bottom",
      spotlightPadding: 4,
      icon: Settings,
      iconColor: "text-gray-600",
      iconBgColor: "bg-gray-100 dark:bg-gray-900/30",
      type: "tooltip",
    },
    {
      id: "create-project",
      title: "Create New Project",
      description: "Click this button to start a new project. You'll enter project details, assign team members, and set up initial documents.",
      targetSelector: "[data-testid='create-project'], button:has(svg.lucide-plus), button[aria-label*='create' i], button[aria-label*='new' i]",
      placement: "bottom-end",
      spotlightPadding: 8,
      icon: Plus,
      iconColor: "text-green-600",
      iconBgColor: "bg-green-100 dark:bg-green-900/30",
      type: "spotlight",
      highlightActions: [
        {
          label: "Create Project",
          onClick: () => {},
          variant: "default",
          icon: Plus,
        },
      ],
    },
    {
      id: "complete",
      title: "You're Ready!",
      description: "You now know how to navigate and manage your projects. Click any project card to get started, or create a new project. Need help? Click the help button anytime.",
      icon: FolderKanban,
      iconColor: "text-primary",
      iconBgColor: "bg-primary/10",
      type: "modal",
    },
  ],
};

export default projectsTour;
