import { Tour } from "../types";
import { 
  FileText, 
  BarChart3,
  Download,
  Calendar,
  Filter,
  Table,
  PieChart,
  TrendingUp,
  DollarSign,
  FileSpreadsheet,
  Printer
} from "lucide-react";

/**
 * Reports Tour - Cost Reports and analytics features
 */
export const reportsTour: Tour = {
  id: "reports-tour",
  name: "Reports Guide",
  description: "Learn how to generate and analyze project reports",
  route: "/reports",
  triggerOnFirstVisit: true,
  autoStart: true,
  showOnce: true,
  priority: 7,
  steps: [
    {
      id: "welcome",
      title: "Welcome to Reports",
      description: "Generate comprehensive reports for your projects including cost breakdowns, material summaries, and progress tracking. Reports can be exported to PDF or Excel.",
      icon: FileText,
      iconColor: "text-primary",
      iconBgColor: "bg-primary/10",
      type: "modal",
    },
    {
      id: "report-types",
      title: "Report Types",
      description: "Choose from various report types: Cost Summary, Material Take-off, Cable Schedule, BOQ Comparison, and more. Each report is tailored for specific use cases.",
      targetSelector: "[data-testid='report-types'], .report-type-selector, [role='tablist']",
      placement: "bottom",
      spotlightPadding: 8,
      icon: FileSpreadsheet,
      iconColor: "text-blue-600",
      iconBgColor: "bg-blue-100 dark:bg-blue-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "date-range",
      title: "Date Range Selection",
      description: "Select the date range for your report. Choose from presets (This Month, Quarter, Year) or set custom dates for precise reporting periods.",
      targetSelector: "[data-testid='date-picker'], .date-range-picker, button[aria-label*='date']",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Calendar,
      iconColor: "text-purple-600",
      iconBgColor: "bg-purple-100 dark:bg-purple-900/30",
      type: "spotlight",
    },
    {
      id: "filters",
      title: "Report Filters",
      description: "Narrow down report data by project, client, status, or category. Multiple filters can be combined for detailed analysis.",
      targetSelector: "[data-testid='report-filters'], .filter-panel, .report-filters",
      placement: "right",
      spotlightPadding: 8,
      icon: Filter,
      iconColor: "text-emerald-600",
      iconBgColor: "bg-emerald-100 dark:bg-emerald-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "data-table",
      title: "Report Data",
      description: "View detailed data in the table. Click column headers to sort. Expandable rows show additional breakdowns and calculations.",
      targetSelector: "[data-testid='report-table'], table, .data-table",
      placement: "top",
      spotlightPadding: 8,
      icon: Table,
      iconColor: "text-amber-600",
      iconBgColor: "bg-amber-100 dark:bg-amber-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "charts",
      title: "Visual Analytics",
      description: "Charts provide visual insights into your data. Toggle between different chart types (bar, pie, line) to see trends and distributions.",
      targetSelector: "[data-testid='charts'], .chart-container, .recharts-wrapper",
      placement: "left",
      spotlightPadding: 8,
      icon: PieChart,
      iconColor: "text-cyan-600",
      iconBgColor: "bg-cyan-100 dark:bg-cyan-900/30",
      type: "spotlight",
    },
    {
      id: "summary-metrics",
      title: "Summary Metrics",
      description: "Key totals and metrics are displayed at the top. See total costs, quantities, margins, and comparisons to budget at a glance.",
      targetSelector: "[data-testid='summary-cards'], .summary-metrics, .metric-cards",
      placement: "bottom",
      spotlightPadding: 8,
      icon: DollarSign,
      iconColor: "text-green-600",
      iconBgColor: "bg-green-100 dark:bg-green-900/30",
      type: "spotlight",
    },
    {
      id: "export-options",
      title: "Export Reports",
      description: "Export your report to PDF for professional documents or Excel for further analysis. Both formats include all data and charts.",
      targetSelector: "[data-testid='export-buttons'], .export-options, button[aria-label*='export']",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Download,
      iconColor: "text-indigo-600",
      iconBgColor: "bg-indigo-100 dark:bg-indigo-900/30",
      type: "spotlight",
      highlightActions: [
        {
          label: "Export PDF",
          onClick: () => {},
          variant: "outline",
          icon: FileText,
        },
        {
          label: "Export Excel",
          onClick: () => {},
          variant: "outline",
          icon: FileSpreadsheet,
        },
      ],
    },
    {
      id: "complete",
      title: "Reports Ready!",
      description: "You're now equipped to generate powerful reports. Use these insights to track project health, manage costs, and make informed decisions.",
      icon: BarChart3,
      iconColor: "text-primary",
      iconBgColor: "bg-primary/10",
      type: "modal",
    },
  ],
};

export default reportsTour;
