import { Tour } from "../types";
import { 
  Settings, 
  User,
  Bell,
  Palette,
  Shield,
  Building,
  CreditCard,
  Globe,
  BookOpen,
  Save
} from "lucide-react";

/**
 * Settings Tour - Application and user settings
 */
export const settingsTour: Tour = {
  id: "settings-tour",
  name: "Settings Guide",
  description: "Learn how to customize your application experience",
  route: "/settings",
  triggerOnFirstVisit: true,
  autoStart: true,
  showOnce: true,
  priority: 3,
  steps: [
    {
      id: "welcome",
      title: "Settings Center",
      description: "Customize your experience, manage your profile, and configure project defaults. Changes are saved automatically.",
      icon: Settings,
      iconColor: "text-primary",
      iconBgColor: "bg-primary/10",
      type: "modal",
    },
    {
      id: "tabs",
      title: "Settings Categories",
      description: "Settings are organized into tabs. Each tab focuses on a specific area: Profile, Appearance, Notifications, Project Defaults, and more.",
      targetSelector: "[role='tablist'], .settings-tabs, .tabs-list",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Settings,
      iconColor: "text-blue-600",
      iconBgColor: "bg-blue-100 dark:bg-blue-900/30",
      type: "spotlight",
      allowInteraction: true,
    },
    {
      id: "profile",
      title: "Profile Settings",
      description: "Update your name, email, photo, and contact information. Your profile is visible to team members on shared projects.",
      targetSelector: "[data-testid='profile-settings'], .profile-section, [role='tabpanel']:first-child",
      placement: "right",
      spotlightPadding: 8,
      icon: User,
      iconColor: "text-emerald-600",
      iconBgColor: "bg-emerald-100 dark:bg-emerald-900/30",
      type: "spotlight",
    },
    {
      id: "appearance",
      title: "Appearance",
      description: "Choose your preferred theme (light, dark, or system), accent color, and display density. Changes apply immediately.",
      targetSelector: "[data-testid='appearance-tab'], button:has-text('Appearance'), [role='tab'][aria-label*='appearance' i]",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Palette,
      iconColor: "text-purple-600",
      iconBgColor: "bg-purple-100 dark:bg-purple-900/30",
      type: "spotlight",
    },
    {
      id: "notifications",
      title: "Notification Preferences",
      description: "Control what notifications you receive and how: email, in-app, or both. Set quiet hours and priority levels.",
      targetSelector: "[data-testid='notifications-tab'], button:has-text('Notifications'), [role='tab'][aria-label*='notification' i]",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Bell,
      iconColor: "text-amber-600",
      iconBgColor: "bg-amber-100 dark:bg-amber-900/30",
      type: "spotlight",
    },
    {
      id: "project-defaults",
      title: "Project Defaults",
      description: "Set default values for new projects: preferred units, calculation standards, report templates, and team assignments.",
      targetSelector: "[data-testid='defaults-tab'], button:has-text('Defaults'), [role='tab'][aria-label*='default' i]",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Building,
      iconColor: "text-cyan-600",
      iconBgColor: "bg-cyan-100 dark:bg-cyan-900/30",
      type: "spotlight",
    },
    {
      id: "security",
      title: "Security",
      description: "Manage your password, enable two-factor authentication, and view active sessions. Keep your account secure.",
      targetSelector: "[data-testid='security-tab'], button:has-text('Security'), [role='tab'][aria-label*='security' i]",
      placement: "bottom",
      spotlightPadding: 8,
      icon: Shield,
      iconColor: "text-red-600",
      iconBgColor: "bg-red-100 dark:bg-red-900/30",
      type: "spotlight",
    },
    {
      id: "guides-tours",
      title: "Guides & Tours",
      description: "Replay walkthroughs, reset hints, and manage your onboarding progress. Great if you need a refresher on any feature.",
      targetSelector: "[data-testid='guides-tab'], button:has-text('Guides'), [role='tab'][aria-label*='guide' i]",
      placement: "bottom",
      spotlightPadding: 8,
      icon: BookOpen,
      iconColor: "text-indigo-600",
      iconBgColor: "bg-indigo-100 dark:bg-indigo-900/30",
      type: "spotlight",
    },
    {
      id: "auto-save",
      title: "Auto-Save",
      description: "Settings are saved automatically as you make changes. Look for the checkmark confirmation after each change.",
      icon: Save,
      iconColor: "text-green-600",
      iconBgColor: "bg-green-100 dark:bg-green-900/30",
      type: "modal",
    },
    {
      id: "complete",
      title: "Settings Complete!",
      description: "Your settings are configured. Return here anytime to adjust preferences. Changes sync across all your devices.",
      icon: Settings,
      iconColor: "text-primary",
      iconBgColor: "bg-primary/10",
      type: "modal",
    },
  ],
};

export default settingsTour;
