import { useMemo } from 'react';
import type { EquipmentItem, SupplyLine, Containment } from '../types';
import type { TakeoffCounts } from '../components/LinkToFinalAccountDialog';
import type { DbCircuitMaterial } from '@/components/circuit-schedule/hooks/useDistributionBoards';
import { formatBOQSection, type BOQSection } from '@/components/circuit-schedule/utils/electricalMaterialUtils';

export interface CircuitMaterialSummary {
  count: number;
  totalLength: number;
  grossLength: number;
  boqSection: BOQSection | null;
  unit: string;
  isAutoGenerated: boolean;
}

export function useTakeoffCounts(
  equipment: EquipmentItem[],
  lines: SupplyLine[],
  containment: Containment[],
  circuitMaterials?: DbCircuitMaterial[]
): TakeoffCounts {
  return useMemo(() => {
    // Count equipment by type
    const equipmentCounts: Record<string, number> = {};
    for (const item of equipment) {
      const type = item.type;
      equipmentCounts[type] = (equipmentCounts[type] || 0) + 1;
    }

    // Sum containment by type
    const containmentLengths: Record<string, number> = {};
    for (const item of containment) {
      const type = item.type;
      containmentLengths[type] = (containmentLengths[type] || 0) + item.length;
    }

    // Aggregate cables by type (from canvas lines)
    const cableCounts: Record<string, { count: number; totalLength: number }> = {};
    for (const line of lines) {
      if (line.type === 'lv' && line.cableType) {
        const type = line.cableType;
        if (!cableCounts[type]) {
          cableCounts[type] = { count: 0, totalLength: 0 };
        }
        cableCounts[type].count += 1;
        cableCounts[type].totalLength += line.length || 0;
      }
    }

    // Aggregate circuit wiring materials from db_circuit_materials
    // Group by BOQ section and material description
    const circuitWiring: Record<string, CircuitMaterialSummary> = {};
    
    if (circuitMaterials && circuitMaterials.length > 0) {
      for (const material of circuitMaterials) {
        // Skip auto-generated supporting materials in main summary (they're counted separately)
        if (material.is_auto_generated) continue;
        
        const description = material.description || '';
        const boqSection = material.boq_section as BOQSection | null;
        const unit = material.unit || 'm';
        
        // Create a grouping key based on material type
        let groupKey = '';
        
        // Try to extract cable type from the beginning of description
        const gpMatch = description.match(/^([\d.]+mm\s*GP)/i);
        const cableMatch = description.match(/^([\d.]+mm\s*\S+)/i);
        
        if (gpMatch) {
          groupKey = gpMatch[1];
        } else if (cableMatch) {
          groupKey = cableMatch[1];
        } else {
          // Use the first part of description for grouping
          groupKey = description.split(' - ')[0] || description;
        }
        
        // Add BOQ section prefix for proper categorization
        const displayKey = boqSection ? `${groupKey}` : groupKey;
        
        if (displayKey) {
          if (!circuitWiring[displayKey]) {
            circuitWiring[displayKey] = { 
              count: 0, 
              totalLength: 0, 
              grossLength: 0,
              boqSection,
              unit,
              isAutoGenerated: false
            };
          }
          circuitWiring[displayKey].count += 1;
          
          // Use gross quantity if available (includes wastage), otherwise calculate
          const netLength = material.quantity || 0;
          const grossLength = material.gross_quantity || netLength;
          
          // For GP wires, quantity is path length - multiply by 3 for total wire
          const isGPWire = description.toLowerCase().includes('gp');
          circuitWiring[displayKey].totalLength += isGPWire ? netLength * 3 : netLength;
          circuitWiring[displayKey].grossLength += isGPWire ? grossLength * 3 : grossLength;
        }
      }
    }

    return {
      equipment: equipmentCounts,
      containment: containmentLengths,
      cables: cableCounts,
      circuitWiring,
    };
  }, [equipment, lines, containment, circuitMaterials]);
}
