// Electrical Material Categorization and Wastage Utilities
// Based on standard electrical contracting best practices

export type MaterialCategory = 'cable' | 'containment' | 'termination' | 'accessory' | 'fitting' | 'distribution';
export type BOQSection = 'CABLES' | 'CONDUITS' | 'DISTRIBUTION' | 'FITTINGS' | 'ACCESSORIES' | 'TERMINATIONS';
export type InstallationStatus = 'planned' | 'installed' | 'verified' | 'invoiced';

export interface MaterialCategoryInfo {
  category: MaterialCategory;
  boqSection: BOQSection;
  wastagePercent: number;
  description: string;
}

// Net contract - no wastage factors applied
// What is measured is what is installed and claimed
export const WASTAGE_FACTORS: Record<MaterialCategory, number> = {
  cable: 0,
  containment: 0,
  termination: 0,
  accessory: 0,
  fitting: 0,
  distribution: 0,
};

// Map material descriptions to categories
export function categorizeMaterial(description: string): MaterialCategoryInfo {
  const desc = description.toLowerCase();
  
  // Cable patterns
  if (desc.includes('mm gp') || desc.includes('mm²') || desc.includes('xlpe') || 
      desc.includes('pvc') || desc.includes('swa') || desc.includes('cable') ||
      desc.includes('earth') || desc.includes('neutral') || desc.includes('live')) {
    return {
      category: 'cable',
      boqSection: 'CABLES',
      wastagePercent: WASTAGE_FACTORS.cable,
      description: 'Low voltage cables and wiring'
    };
  }
  
  // Containment patterns
  if (desc.includes('trunking') || desc.includes('conduit') || desc.includes('tray') ||
      desc.includes('ladder') || desc.includes('duct') || desc.includes('skirting') ||
      desc.includes('sleeve')) {
    return {
      category: 'containment',
      boqSection: 'CONDUITS',
      wastagePercent: WASTAGE_FACTORS.containment,
      description: 'Cable containment systems'
    };
  }
  
  // Termination patterns
  if (desc.includes('gland') || desc.includes('lug') || desc.includes('ferrule') ||
      desc.includes('terminal') || desc.includes('connector') || desc.includes('crimp')) {
    return {
      category: 'termination',
      boqSection: 'TERMINATIONS',
      wastagePercent: WASTAGE_FACTORS.termination,
      description: 'Cable terminations and connections'
    };
  }
  
  // Distribution patterns
  if (desc.includes('db') || desc.includes('distribution') || desc.includes('mcb') ||
      desc.includes('mccb') || desc.includes('isolator') || desc.includes('breaker') ||
      desc.includes('rcd') || desc.includes('surge')) {
    return {
      category: 'distribution',
      boqSection: 'DISTRIBUTION',
      wastagePercent: WASTAGE_FACTORS.distribution,
      description: 'Distribution boards and protection devices'
    };
  }
  
  // Fitting patterns
  if (desc.includes('light') || desc.includes('luminaire') || desc.includes('fitting') ||
      desc.includes('led') || desc.includes('downlight') || desc.includes('panel') ||
      desc.includes('batten') || desc.includes('flood') || desc.includes('spot')) {
    return {
      category: 'fitting',
      boqSection: 'FITTINGS',
      wastagePercent: WASTAGE_FACTORS.fitting,
      description: 'Light fittings and luminaires'
    };
  }
  
  // Default to accessory
  return {
    category: 'accessory',
    boqSection: 'ACCESSORIES',
    wastagePercent: WASTAGE_FACTORS.accessory,
    description: 'Electrical accessories and sundries'
  };
}

// Net contract - gross = net (no wastage calculation)
export function calculateGrossQuantity(netQuantity: number, _wastagePercent: number): {
  wastageQuantity: number;
  grossQuantity: number;
} {
  // No wastage for net contracts
  return { wastageQuantity: 0, grossQuantity: netQuantity };
}

// Generate supporting materials for a cable
export interface SupportingMaterial {
  description: string;
  category: MaterialCategory;
  boqSection: BOQSection;
  unit: string;
  quantity: number;
  isAutoGenerated: true;
}

export function generateCableSupportingMaterials(
  cableDescription: string,
  cableSize: string,
  cableLength: number
): SupportingMaterial[] {
  const materials: SupportingMaterial[] = [];
  const isArmoured = cableDescription.toLowerCase().includes('swa') || 
                     cableDescription.toLowerCase().includes('armoured');
  
  // Cable glands (2 per cable run - one each end)
  if (isArmoured) {
    materials.push({
      description: `Cable gland ${cableSize} - brass CW type`,
      category: 'termination',
      boqSection: 'TERMINATIONS',
      unit: 'Nr',
      quantity: 2,
      isAutoGenerated: true,
    });
    
    // Lock nuts
    materials.push({
      description: `Lock nut ${cableSize}`,
      category: 'accessory',
      boqSection: 'ACCESSORIES',
      unit: 'Nr',
      quantity: 2,
      isAutoGenerated: true,
    });
    
    // Earth tags
    materials.push({
      description: `Earth tag ${cableSize}`,
      category: 'accessory',
      boqSection: 'ACCESSORIES',
      unit: 'Nr',
      quantity: 2,
      isAutoGenerated: true,
    });
  }
  
  // Cable ties (approx 1 per 300mm for support)
  const cableTieCount = Math.ceil(cableLength / 0.3);
  if (cableTieCount > 0) {
    materials.push({
      description: 'Cable tie 200mm black',
      category: 'accessory',
      boqSection: 'ACCESSORIES',
      unit: 'Nr',
      quantity: cableTieCount,
      isAutoGenerated: true,
    });
  }
  
  // Saddles/clips for surface cables (1 per 500mm)
  const saddleCount = Math.ceil(cableLength / 0.5);
  if (saddleCount > 0 && cableLength > 1) {
    materials.push({
      description: `Cable saddle/clip ${cableSize}`,
      category: 'accessory',
      boqSection: 'ACCESSORIES',
      unit: 'Nr',
      quantity: saddleCount,
      isAutoGenerated: true,
    });
  }
  
  // Cable markers (2 per run)
  materials.push({
    description: 'Cable identification marker',
    category: 'accessory',
    boqSection: 'ACCESSORIES',
    unit: 'Nr',
    quantity: 2,
    isAutoGenerated: true,
  });
  
  return materials;
}

// Format BOQ section for display
export function formatBOQSection(section: BOQSection): string {
  const sectionNames: Record<BOQSection, string> = {
    'CABLES': 'Bill 1: Cables & Wiring',
    'CONDUITS': 'Bill 2: Containment & Conduits',
    'DISTRIBUTION': 'Bill 3: Distribution Equipment',
    'FITTINGS': 'Bill 4: Light Fittings',
    'ACCESSORIES': 'Bill 5: Accessories & Sundries',
    'TERMINATIONS': 'Bill 6: Terminations',
  };
  return sectionNames[section] || section;
}

// Get installation status badge color
export function getStatusColor(status: InstallationStatus): string {
  const colors: Record<InstallationStatus, string> = {
    'planned': 'bg-slate-500',
    'installed': 'bg-blue-500',
    'verified': 'bg-green-500',
    'invoiced': 'bg-purple-500',
  };
  return colors[status] || 'bg-gray-500';
}
