import { DesignPurpose, EquipmentType, ContainmentType } from './types';

export interface PurposeConfig {
  name: string;
  description: string;
  equipmentTypes: EquipmentType[];
  defaultContainment?: ContainmentType;
  showPV?: boolean;
  showContainment?: boolean;
  showTasks?: boolean;
  showBoQ?: boolean;
}

export const PURPOSE_CONFIGS: Record<DesignPurpose, PurposeConfig> = {
  [DesignPurpose.BUDGET_MARKUP]: {
    name: 'Budget Markup',
    description: 'General electrical budget estimation',
    equipmentTypes: Object.values(EquipmentType),
    defaultContainment: ContainmentType.CABLE_TRAY,
    showContainment: true,
    showTasks: true,
    showBoQ: true,
  },
  [DesignPurpose.LINE_SHOP]: {
    name: 'Line Shop Markup',
    description: 'Detailed line shop electrical design',
    equipmentTypes: [
      EquipmentType.GENERAL_LIGHT_SWITCH,
      EquipmentType.DIMMER_SWITCH,
      EquipmentType.MOTION_SENSOR,
      EquipmentType.TWO_WAY_LIGHT_SWITCH,
      EquipmentType.WATERTIGHT_LIGHT_SWITCH,
      EquipmentType.LED_STRIP_LIGHT,
      EquipmentType.FLUORESCENT_2_TUBE,
      EquipmentType.FLUORESCENT_1_TUBE,
      EquipmentType.CEILING_FLOODLIGHT,
      EquipmentType.CEILING_LIGHT,
      EquipmentType.POLE_MOUNTED_LIGHT,
      EquipmentType.WALL_MOUNTED_LIGHT,
      EquipmentType.RECESSED_LIGHT_600,
      EquipmentType.RECESSED_LIGHT_1200,
      EquipmentType.FLOODLIGHT,
      EquipmentType.PHOTO_CELL,
      EquipmentType.FLUSH_FLOOR_OUTLET,
      EquipmentType.BOX_FLUSH_FLOOR,
      EquipmentType.SOCKET_16A,
      EquipmentType.SOCKET_DOUBLE,
      EquipmentType.CLEAN_POWER_OUTLET,
      EquipmentType.EMERGENCY_SOCKET,
      EquipmentType.UPS_SOCKET,
      EquipmentType.DATA_SOCKET,
      EquipmentType.TELEPHONE_OUTLET,
      EquipmentType.SINGLE_PHASE_OUTLET,
      EquipmentType.THREE_PHASE_OUTLET,
      EquipmentType.SOCKET_16A_TP,
      EquipmentType.GEYSER_OUTLET,
      EquipmentType.WATER_HEATER_CONTROL,
      EquipmentType.STOVE_OUTLET,
      EquipmentType.FAN,
      EquipmentType.EXTRACTOR_FAN,
      EquipmentType.ELECTRIC_GATE,
      EquipmentType.BELL,
      EquipmentType.SIREN,
      EquipmentType.SMOKE_DETECTOR,
      EquipmentType.SHAVER_SOCKET,
    ],
    defaultContainment: ContainmentType.SLEEVES,
    showContainment: true,
    showTasks: true,
    showBoQ: true,
  },
  [DesignPurpose.PV_DESIGN]: {
    name: 'Solar PV Design',
    description: 'Photovoltaic solar installation',
    equipmentTypes: [
      EquipmentType.INVERTER,
      EquipmentType.DC_COMBINER,
      EquipmentType.AC_DISCONNECT,
    ],
    showPV: true,
    showContainment: false,
    showTasks: true,
    showBoQ: true,
  },
  [DesignPurpose.EXTERNAL_LIGHTING]: {
    name: 'External Lighting',
    description: 'Outdoor lighting design',
    equipmentTypes: [
      EquipmentType.POLE_LIGHT,
      EquipmentType.POLE_MOUNTED_LIGHT,
      EquipmentType.FLOODLIGHT,
      EquipmentType.PHOTO_CELL,
      EquipmentType.MAIN_BOARD,
      EquipmentType.SUB_BOARD,
    ],
    defaultContainment: ContainmentType.SLEEVES,
    showContainment: true,
    showTasks: true,
    showBoQ: true,
  },
  [DesignPurpose.CCTV_NETWORK]: {
    name: 'CCTV & Network',
    description: 'Security and data networking',
    equipmentTypes: [
      EquipmentType.DATA_SOCKET,
      EquipmentType.TELEPHONE_OUTLET,
      EquipmentType.MAIN_BOARD,
      EquipmentType.SUB_BOARD,
    ],
    defaultContainment: ContainmentType.TELKOM_BASKET,
    showContainment: true,
    showTasks: true,
    showBoQ: true,
  },
  [DesignPurpose.POWER_SOCKET_LAYOUT]: {
    name: 'Power & Socket Layout',
    description: 'Power distribution and sockets',
    equipmentTypes: [
      EquipmentType.MAIN_BOARD,
      EquipmentType.SUB_BOARD,
      EquipmentType.SOCKET_16A,
      EquipmentType.SOCKET_DOUBLE,
      EquipmentType.SOCKET_16A_TP,
      EquipmentType.SINGLE_PHASE_OUTLET,
      EquipmentType.THREE_PHASE_OUTLET,
      EquipmentType.GEYSER_OUTLET,
      EquipmentType.STOVE_OUTLET,
      EquipmentType.WATER_HEATER_CONTROL,
      EquipmentType.CLEAN_POWER_OUTLET,
      EquipmentType.EMERGENCY_SOCKET,
      EquipmentType.UPS_SOCKET,
    ],
    defaultContainment: ContainmentType.P2000_TRUNKING,
    showContainment: true,
    showTasks: true,
    showBoQ: true,
  },
};
