// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// OVERRIDE: Hardcoded connection to NEW database (vlw...)
const SUPABASE_URL = "https://vlwbobrzuzrnpdqxfkyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsd2JvYnJ6dXpybnBkcXhma3lnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDU2NDMwNCwiZXhwIjoyMDc2MTQwMzA0fQ.w5kkiJ1Q52ClBSECTp7TkJV47C4XboUvV48GDsP4nsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});